name: Demo AI Test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install Jaclang and dependencies
      - name: Install from source repositories
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/TrueSelph/jvcli.git@2.1.0
          pip install git+https://github.com/TrueSelph/jvserve.git@2.1.0
          pip install git+https://github.com/TrueSelph/jivas.git@2.1.0
          
      # Run Jaclang test cases
      - name: Run Jaclang Tests
        run: |
          jac test actions/jivas/agent_utils_action/agent_utils_action.jac